// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, cart_id, product_id, quantity
`

type AddCartItemParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at
`

func (q *Queries) CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.ProductID)
	return err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at FROM carts
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getCartItemByProduct = `-- name: GetCartItemByProduct :one
SELECT id, cart_id, product_id, quantity FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type GetCartItemByProductParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByProduct, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT
    p.id,
    p.name,
    p.price,
    ci.quantity
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.cart_id = $1
`

type GetCartItemsRow struct {
	ID       uuid.UUID
	Name     string
	Price    pgtype.Numeric
	Quantity int32
}

func (q *Queries) GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items
SET quantity = $3
WHERE cart_id = $1 AND product_id = $2
`

type UpdateCartItemQuantityParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.Exec(ctx, updateCartItemQuantity, arg.CartID, arg.ProductID, arg.Quantity)
	return err
}
