// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type CartItem struct {
	ID        uuid.UUID
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type Category struct {
	ID        int32
	Name      string
	ParentID  pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type Order struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	StatusID        pgtype.Int4
	TotalAmount     pgtype.Numeric
	ShippingAddress string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrderItem struct {
	ID              uuid.UUID
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	PriceAtPurchase pgtype.Numeric
}

type OrderStatus struct {
	ID   int32
	Name string
}

type Payment struct {
	ID            uuid.UUID
	OrderID       uuid.UUID
	Amount        pgtype.Numeric
	Provider      pgtype.Text
	PaymentStatus pgtype.Text
	TransactionID pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   pgtype.Text
	Price         pgtype.Numeric
	StockQuantity int32
	CategoryID    pgtype.Int4
	BrandID       pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	RoleID       pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
