// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	ClearCart(ctx context.Context, cartID uuid.UUID) error
	CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error)
	GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderStatusByName(ctx context.Context, name string) (OrderStatus, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListUserOrders(ctx context.Context, userID uuid.UUID) ([]Order, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
